version: '3.8'

services:

  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "9000:80"

  fastani:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/fastani/Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 1
    volumes:
      - type: bind
        source: $FASTANI_GENOME_DIR
        target: $FASTANI_GENOME_DIR
        read_only: true
